# Generated by Django 4.2.5 on 2023-10-07 22:40

from django.db import migrations
from django.conf import settings


def add_site(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')

    # site domains should probably be a list in settings, but this illustrates my point better
    if settings.IS_HEROKU_APP:
        domains = ["b20-5ae072eaa78c.herokuapp.com"]
    else:
        domains = ["127.0.0.1:8000", "localhost:8000"]

    new_sites = [Site(domain=domain, name=domain) for domain in domains]

    for new_site in new_sites:
        new_site.save()


class Migration(migrations.Migration):

    dependencies = [
        ('deploytest', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.RunPython(add_site),
    ]
