# Generated by Django 4.2.6 on 2023-10-14 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deploytest', '0003_add_google_socialapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.IntegerField()),
                ('description', models.TextField()),
                ('apartment_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('parking', models.BooleanField()),
                ('num_beds', models.IntegerField()),
                ('num_baths', models.IntegerField()),
                ('rent_per_month', models.IntegerField()),
                ('images', models.ImageField(upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]