# Generated by Django 4.2.5 on 2023-10-22 07:40

import address.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        ('deploytest', '0004_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='address',
            field=address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.address'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='images',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='listing',
            name='num_baths',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Number of bathrooms'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='num_beds',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Number of beds'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rent_per_month',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
