# Generated by Django 4.2.5 on 2023-10-31 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploytest', '0005_alter_listing_address_alter_listing_images_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signature',
        ),
    ]
