# Generated by Django 4.2.5 on 2023-11-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploytest', '0006_delete_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
