# Generated by Django 4.2.5 on 2023-11-02 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploytest', '0007_listing_is_approved_listing_is_hidden'),
        ('deploytest', '0007_remove_listing_images_remove_listing_place_id'),
    ]

    operations = [
    ]
