# Generated by Django 4.2.5 on 2023-11-04 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploytest', '0008_merge_20231102_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
