# Generated by Django 4.2.5 on 2023-11-04 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploytest', '0008_message'),
        ('deploytest', '0009_listing_is_reviewed'),
    ]

    operations = [
    ]
