# Generated by Django 4.2.5 on 2023-11-07 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploytest', '0008_amenity'),
        ('deploytest', '0010_merge_0008_message_0009_listing_is_reviewed'),
    ]

    operations = [
    ]
