# Generated by Django 4.2.5 on 2023-11-09 15:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploytest', '0011_merge_20231107_0337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='description',
            new_name='apartment_description',
        ),
        migrations.AddField(
            model_name='listing',
            name='lease_end',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='listing',
            name='lease_start',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(default='Roommate', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Utility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility', models.CharField(max_length=50)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploytest.listing')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=50)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploytest.listing')),
            ],
        ),
    ]
