# Generated by Django 4.2.5 on 2023-11-09 20:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploytest', '0012_rename_description_listing_apartment_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='square_feet',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Square feet'),
        ),
    ]
