# Generated by Django 4.2.5 on 2023-11-10 01:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploytest', '0013_listing_square_feet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utility',
            name='utility',
        ),
        migrations.AddField(
            model_name='utility',
            name='cable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utility',
            name='electricity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utility',
            name='gas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utility',
            name='heat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utility',
            name='internet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utility',
            name='phone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utility',
            name='security',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utility',
            name='sewer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utility',
            name='trash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utility',
            name='water',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='square_feet',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Square feet (Optional)'),
        ),
    ]
