# Generated by Django 4.2.5 on 2023-11-10 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploytest', '0014_remove_utility_utility_utility_cable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas', models.BooleanField(default=False)),
                ('water', models.BooleanField(default=False)),
                ('heat', models.BooleanField(default=False)),
                ('trash', models.BooleanField(default=False)),
                ('sewer', models.BooleanField(default=False)),
                ('electricity', models.BooleanField(default=False)),
                ('internet', models.BooleanField(default=False)),
                ('security', models.BooleanField(default=False)),
                ('cable', models.BooleanField(default=False)),
                ('phone', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Utility',
        ),
        migrations.AddField(
            model_name='listing',
            name='utilities',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='deploytest.utilities'),
        ),
    ]
