# Generated by Django 4.2.5 on 2023-11-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploytest', '0015_utilities_delete_utility_listing_utilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='place_id',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='utilities',
            name='cable',
            field=models.BooleanField(default=False, verbose_name='Cable'),
        ),
        migrations.AlterField(
            model_name='utilities',
            name='electricity',
            field=models.BooleanField(default=False, verbose_name='Electricity'),
        ),
        migrations.AlterField(
            model_name='utilities',
            name='gas',
            field=models.BooleanField(default=False, verbose_name='Gas'),
        ),
        migrations.AlterField(
            model_name='utilities',
            name='heat',
            field=models.BooleanField(default=False, verbose_name='Heat'),
        ),
        migrations.AlterField(
            model_name='utilities',
            name='internet',
            field=models.BooleanField(default=False, verbose_name='Internet'),
        ),
        migrations.AlterField(
            model_name='utilities',
            name='phone',
            field=models.BooleanField(default=False, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='utilities',
            name='security',
            field=models.BooleanField(default=False, verbose_name='Security'),
        ),
        migrations.AlterField(
            model_name='utilities',
            name='sewer',
            field=models.BooleanField(default=False, verbose_name='Sewer'),
        ),
        migrations.AlterField(
            model_name='utilities',
            name='trash',
            field=models.BooleanField(default=False, verbose_name='Trash'),
        ),
        migrations.AlterField(
            model_name='utilities',
            name='water',
            field=models.BooleanField(default=False, verbose_name='Water'),
        ),
    ]
